### ISSUE TITLE
The most recent version of Imagemagick causes .jp2 conversions to fail

### ISSUE THREAD

**Issue by bmaddy** [curationexperts/riiif#17]
Only happens when the source url/path is for a file that doesn't have an extension. The file is downloaded and saved locally as a file without an extension. The new version of ImageMagick uses the file extension to know that it's a .jp2 file and then can't convert it.

ImageMagick 6.8.7-0 works
ImageMagick 6.8.9-5 doesn't work

**Comment by jcoyne** [comment]
Due to https://github.com/ImageMagick/ImageMagick/issues/28
