### ISSUE TITLE
Support IIIF Image API version 2.0 (and soon[?] 2.1)

### ISSUE THREAD

**Issue by anarchivist** [curationexperts/riiif#22]
I think it'd be great for Riiif to support version 2.0 of the Image API. I do realize that 2.1 is relatively speaking around the corner. My time is still a bit up in the air, but I may be able to assist with this.

**Comment by jcoyne** [comment]
Yes, someone should do that ;)

**Comment by jrhoads** [comment]
Is this still an issue?
I see a bunch of commits in Oct/Nov 2015 that appear to be making this transition to 2.0 (Ex. e6b6996d4952407818ceec4419e140f3b854fe80 )

**Comment by anarchivist** [comment]
I'm guessing it's no longer an issue, but riiif's 2.0 compliance seems to be only level 1 based on that commit.
