### ISSUE TITLE
Huge ImageMagick temp files?

### ISSUE THREAD

**Issue by benwbrum** [curationexperts/riiif#24]
I've incorporated riiif into `benwbrum/fromthepage` and am delighted -- great stuff!

I do have one problem, however -- it seems that riiif generates enormous temporary files through ImageMagick, as I discovered when /tmp filled up after I pointed Mirador at my production server:
```
-rw------- 1 fromthepage fromthepage 160563200 Oct  1 16:13 magick-27931xH7AjyMNUao2
-rw------- 1 fromthepage fromthepage 211680000 Oct  1 16:23 magick-289004VQUiuNCmDJP
-rw------- 1 fromthepage fromthepage 169344000 Oct  1 16:23 magick-28900WDKGqb6QaBEW
-rw------- 1 fromthepage fromthepage 169344000 Oct  1 16:23 magick-28994_23iC4nXagbZ
-rw------- 1 fromthepage fromthepage 211680000 Oct  1 16:23 magick-28994lUryuxd1NOhW
-rw------- 1 fromthepage fromthepage 169344000 Oct  1 16:24 magick-29008e7j_rm3OnQ2c
-rw------- 1 fromthepage fromthepage 211680000 Oct  1 16:24 magick-29008h3tmz3TbuDfo
-rw------- 1 fromthepage fromthepage 211680000 Oct  1 16:29 magick-29866GOHyDHAKV7Wi
-rw------- 1 fromthepage fromthepage 169344000 Oct  1 16:29 magick-29866SM0tazaV00F1
```

Any guess as to what's causing this or how to remediate it?

**Comment by jcoyne** [comment]
That sounds like imagemagick is crashing.  I'm going to guess this is because you exceeded the memory limit. See http://www.imagemagick.org/script/resources.php for configuration parameters.  Another possibility is that the Linux Out Of Memory (OOM) killer is reaping the process.

**Comment by benwbrum** [comment]
That hadn't occurred to me at all.

Thanks for the help -- I'll try to do some controlled tests to see what's
going on.

**Comment by benwbrum** [comment]
Thanks -- we got everything working nicely.

**Comment by cbeer** [comment]
@benwbrum what was the cause / fix?

**Comment by benwbrum** [comment]
I can't be 100% sure, but I'd upgraded Imagemagick between spotting the
problem and discovering that it seemed to be fixed, so that's my best guess.
