### ISSUE TITLE
"bin/rails:6: warning: already initialized constant APP_PATH” warning

### ISSUE THREAD

**Issue by hweng** [curationexperts/riiif#25]
I've created a new rails project, installed imagemagick and Riiif gem and bundle install.
When I run rails s I'm getting this error:

"bin/rails:7: warning: already initialized constant APP_PATH
/Users/hweng/git/test_iiif/bin/rails:7: warning: previous definition of APP_PATH was here”

I've tried a number of thing to fix this error, finally the rails server can start after removing the following code from bin/rails:

```ruby
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError
end
```

Is that due to some conflict with Spring?  Is there any working example which use riiif and could you provide its github link?  Thanks!

**Comment by jcoyne** [comment]
That is a warning, not an error. You can ignore it

**Comment by hweng** [comment]
But the rails server can not start with that warning.

**Comment by jcoyne** [comment]
What particular rails server are you talking about?  How are you starting it?

**Comment by hweng** [comment]
I run “rails s” to start server on my Mac,  and use
WEBrick server,
ruby 2.1.2
Rails 4.2.4

The  WEBrick server can start after removing the above code from bin/rails, as I mentioned.

We just started looking into IIIF framework, and I’m looking for the options for image server.  
Do you have some detail instructions to set up the image server using riiif? And would you  point to some github links if there is any working example available? Thanks!

**Comment by jcoyne** [comment]
I've never seen those warnings. And I'm unable to duplicate the issue you are seeing.  Here's a project that is using it: 
https://github.com/curationexperts/goldenseal
https://github.com/KelvinSmithLibrary/absolute
https://github.com/curationexperts/alexandria-v2

Here's a sample endpoint: http://sandbox.curationexperts.com/images/c9%2F50%2F2d%2F55%2Fc9502d55-9fe2-4621-9a8b-515e56fcc92c%2Foriginal/full/600,/0/native.jpg

**Comment by hweng** [comment]
@jcoyne, Thanks for the links!
