### ISSUE TITLE
default Image.info_service always returns empty strings for dimensions

### ISSUE THREAD

**Issue by dunn** [curationexperts/riiif#33]
`Image.info_service` is used when the region is not `full`.  In my testing, it always returns `""` as the width and height, instead of the actual dimensions.  I'm not sure why this is happening; it may be `Rails.cache` overriding the `image` variable, but that's just a guess.  

For my use at least, just removing the info_service code entirely restores the correct behavior: https://github.com/dunn/riiif/commit/6253bfa93c485f2f2d4472b5266f3ed01f0bb585

What are the use-cases for overriding that method?  It seems risky, since `#decode_region` depends on it.

**Comment by jcoyne** [comment]
Your image service is set to return empty strings: https://github.com/curationexperts/alexandria/blob/master/config/initializers/riiif_initializer.rb#L3-L5

You probably want to change that to fetch values from solr, like this: https://github.com/projecthydra-labs/lerna/blob/master/config/initializers/riiif.rb#L8-L12

**Comment by dunn** [comment]
> Your image service is set to return empty strings

Oh, that explains it.  Why did you do that?

**Comment by jcoyne** [comment]
I can't recall, possibly because it wasn't indexed at that point.
