### ISSUE TITLE
undefined method `merge' for #<struct Riiif::ImageInformation

### ISSUE THREAD

**Issue by bess** [curationexperts/riiif#50]
With riiif 1.1.2, I encounter a bug when rendering info.json manifests. It can't run #merge on a Riiif::ImageInformation struct. The bug is fixed if I add a #to_h, like this:

`        render json: image.info.to_h.merge(server_info), content_type: 'application/ld+json'
`

PR forthcoming.

![screen shot 2017-03-15 at 2 13 10 pm](https://cloud.githubusercontent.com/assets/65608/23971080/a853135c-0989-11e7-8a9a-595b0c9a9fc6.png)

**Comment by jcoyne** [comment]
Looks like a resonable fix.
