### ISSUE TITLE
"not found error" is used for unauthorized responses

### ISSUE THREAD

**Issue by dunn** [curationexperts/riiif#61]
This is probably something I can do next week, but writing it down here.

When `#show` gets an `unauthorized` response from the AuthService, the same "Not found image doesn't exist" error is raised as for actual `ImageNotFoundError`s: https://github.com/curationexperts/riiif/blob/master/app/controllers/riiif/images_controller.rb#L15-L21

ImageNotFoundError should be re-raised instead of a plain RuntimeError, and there should be a distinct error class for unauthorized.

**Comment by jcoyne** [comment]
This only happens when `Riiif.not_found_image` has not been configured. https://github.com/curationexperts/riiif/blob/master/app/controllers/riiif/images_controller.rb#L92

**Comment by dunn** [comment]
If that is configured, then `not/found.png` is also sent for unauthorized requests.  That seems strange too.

**Comment by jcoyne** [comment]
@dunn I agree, that whole piece of code could use some reworking, I was just adding that as a clarifying point about how to reproduce.
